name: Deploy Image to EC2

on:
  workflow_dispatch:
    inputs:
      version:
        description: "deploy"
        required: true
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: |
          echo "test"

    #   - name: Docker Login
    #     run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    #   - name: Build & Push Docker Image
    #     run: |
    #       docker build -t ghcr.io/limits1214/my-app:${{ github.event.inputs.version }} .
    #       docker push ghcr.io/limits1214/my-app:${{ github.event.inputs.version }}

    #   - name: SSH to EC2 and Deploy
    #     uses: appleboy/ssh-action@v1
    #     with:
    #       host: ${{ secrets.EC2_HOST }}
    #       username: ubuntu
    #       key: ${{ secrets.EC2_SSH_KEY }}
    #       script: |
    #         docker pull ghcr.io/limits1214/my-app:${{ github.event.inputs.version }}
    #         docker stop my-app || true
    #         docker rm my-app || true
    #         docker run -d --name my-app -p 4000:4000 ghcr.io/limits1214/my-app:${{ github.event.inputs.version }}
